### PR TITLE
Enables building odata.net with VS 2019

### LINKED ISSUE #1560: Cannot build with VS 2019
Hi,

I have a VS 2019 only machine and I'm trying to build this repo.
I tried to work on it (checkout my [branch](https://github.com/weitzhandler/odata.net/tree/vs2019)), by updating the appropriate paths in the build.ps1 file, but I'm still getting errors.
I've updated this issue in MSBuild, but I felt it's appropriate tracking this from here as well.
Any advice on getting this repo built with VS2019?

My goal is to be able to debug this repo. It's shipped to NuGet without its assemblies and I'm using a dependent package (`Simple.OData.Client`) I'm having issues with, and I've spent hours trying to make it debuggable.

Please help me out here, I'm willing to work on this but need advise and guidance.

### Reproduce steps

On a machine with VS 2019,
- Clone the repo try to call `build` command from the main repo folder

Or
- Call [`build.ps1`](https://github.com/weitzhandler/odata.net/blob/vs2019/build.ps1) on my branch, which is an updated version that determines VS version and sets MSBuild paths appropriately, and in addition self-updates NuGet.

### Expected result

Successfully build odata.net with VS 2019

### Actual result

Building this repo with VS2019 fails

### PR DESCRIPTION
**Pull request by weitzhandler**
Fixes #1560

### CODE REVIEW

**Comment by robertmclaws** [comment]
The formatting changes make it very difficult to see what was actually changed to enable this functionality.

**Comment by weitzhandler** [comment]
Yeah. After committing I realized that. I'm gonna revert them.
It happened because I often use <kbd>Ctrl</kbd><kbd>K</kbd>+<kbd>Ctrl</kbd><kbd>D</kbd>

**Comment by weitzhandler** [comment]
Formatting removed.
I think it might be a good idea to add a _.editorconfig_ file to the project for easy and conventional formatting. Should I? Can I do this in this branch?

**Comment by weitzhandler** [comment]
Thanks @robertmclaws, I removed the formatting.
I think it might be a good idea to add a _.editorconfig_ file to the project for easy and conventional formatting. Should I? Can I do this in this branch?

Besides, I got some progress as soon as https://github.com/microsoft/msbuild/issues/4786 was solved (thanks @jmarolf). We should update the documentation so that the prerequisites include ".NET Portable Library targeting pack".

**Comment by jmarolf** [comment]
@weitzhandler you can also add a [vsconfig](https://docs.microsoft.com/en-us/visualstudio/install/import-export-installation-configurations?view=vs-2019#automatically-install-missing-components) file so Visual Studio automatically installs the tools when you open the solution

**Comment by weitzhandler** [comment]
> @weitzhandler you can also add a [vsconfig](https://docs.microsoft.com/en-us/visualstudio/install/import-export-installation-configurations?view=vs-2019#automatically-install-missing-components) file so Visual Studio automatically installs the tools when you open the solution

Sounds like a great idea, but since I have a lot of irrelevant stuff in my installation, I think it's better to deal with it in separate issue, which I'll do once I'm done with my current goal: being able to debug this repo when installed via its dependent packages, from NuGet (such as Simple.OData.Client).

**Comment by weitzhandler** [comment]
> @weitzhandler you can also add a [vsconfig](https://docs.microsoft.com/en-us/visualstudio/install/import-export-installation-configurations?view=vs-2019#automatically-install-missing-components) file so Visual Studio automatically installs the tools when you open the solution

Sounds like something that could have saved a lot of frustration here. Lemme open a separate issue/PR about that.

**Comment by weitzhandler** [comment]
Now I'm rather getting a gazillion of these errors:
>  10>EXEC : warning : Could not find a part of the path 'D:\Users\Shimmy\Source\Repos\odata.net\sln\ \packages\xunit.assert.2.1.0'. [D:\Users\Shimmy\Source\Repos\odata.net\test\FunctionalTests\Microsoft.OData.Client.Tests\Microsoft.OData.Client.Tests.csproj]

And

>    10>D:\Users\Shimmy\Source\Repos\odata.net\sln\.nuget\NuGet.targets(100,9): error : Could not find a part of the path 'D:\Users\Shimmy\Source\Repos\odata.net\sln\ \packages\xunit.assert.2.1.0'. [D:\Users\Shimmy\Source\Repos\odata.net\test\FunctionalTests\Microsoft.OData.Client.Tests\Microsoft.OData.Client.Tests.csproj]

Is it the space and redundant slash between `sln\` and `\packages`? Looks like the correct path is passed to MSBuild.
I want to make this work, but unfortunately I'm pretty noob when it comes to build scripts and could use help.

image

**Comment by robertmclaws** [comment]
I will talk to the team about implementing SourceLink and NuGet Symbol packages during our meeting tomorrow. That should allow you to be able to debug this repo without whatever hassles you're currently dealing with.

**Comment by weitzhandler** [comment]
Thank you so much for this, and for everything, @robertmclaws!

**Comment by odero** [comment]
@weitzhandler are you still working on this?

**Comment by weitzhandler** [comment]
> @weitzhandler are you still working on this?

I'm currently busy with a different WPF project, so not dealing with OData at the moment, sorry.

**Comment by weitzhandler** [comment]
@robertmclaws @mikepizzo What's up?

Can we get this running? At the moment no one can use odata.net, as it doesn't build on VS 2019, due to the differences in the MSBuild system.

**Comment by weitzhandler** [comment]
> @weitzhandler are you still working on this?

I'd love to. I guess I'd need some direction on where this is headed. We should delete the legacy build options and update the docs on building if we're not using it. This is major confusion.

**Comment by mikepizzo** [comment]
With the new pipeline, OData.net should fully support building with VS2019.  thanks!

**Comment by weitzhandler** [comment]
Thank you @mikepizzo!

**Pull request closed without merging**
