### PR TITLE
Fix ArgumentNullException on Any in ODataUriResolver #1671

### PR DESCRIPTION
**Pull request by PatrickHofman**
### Issues

This pull request fixes issue #1671.

### Description

Fix the argument exception.

### Checklist (Uncheck if it is not completed)

- [ ] *Test cases added*
- [ ] *Build and test with one-click build and test script passed*

### Additional work necessary

None.

### CODE REVIEW

**Comment by gathogojr** [comment]
@PatrickHofman Would you be willing and available to implement the change like @g2mula suggested while also adding the test? We discussed internally and agreed that is a pragmatic and least contentious fix to the issue. If you're not available to follow it through we can slot it into our TODO

**Comment by gathogojr** [comment]
@PatrickHofman Kindly note that this issue is being looked into at the moment. One observation made though is that the only scenario that will result into a `null` being returned from `FindDeclaredOperationImports` is if the Edm model has no entity container...
```
            new EdmModel().FindDeclaredOperationImports("NonExistingOperationImports");
```

Otherwise if the entity container is set and the passed operation import is not found, the call to `container.FindOperationImportsExtended(qualifiedName);` returns a collection for all execution paths. Hopefully the result you're observing is not caused by a subtle bug in your code. For now the fix will involve ensuring the method never returns a `null`.
If you have made any further observation that point to any other scenario that would result into a `null` being returned, kindly share with us so we can do further investigation

**Comment by PatrickHofman** [comment]
@gathogojr Sorry I didn't have any time to respond the last few days. It has been quite busy here.

The problem occurred on my end when I requested a table that didn't exist. As far as I can recollect the exception was ignored later on, but I wondered why it was thrown in the first place and so I found this problem. Thanks for looking in to it. I don't think I will have the time to fix this soon, also because I am not familiar with the project itself. If you can pick this up, it would be highly appreciated.

**Comment by gathogojr** [comment]
@PatrickHofman No problem. Already did a PR to in the list ensure that the method never responds with a null https://github.com/OData/odata.net/pull/1690. I'll merge it as soon as I get approvals

**Comment by gathogojr** [comment]
Fix implemented in this PR https://github.com/OData/odata.net/pull/1690

**Pull request closed without merging**
