### PR TITLE
Expose additional Preference Headers

### PR DESCRIPTION
**Pull request by JefWight**
Adds the odata.track-changes, odata.maxpagesize, and
odata.continue-on-error preference headers.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@JefWight__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@JefWight__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by dingeins** [comment]
Confirmed that Jeff is an Microsoft FTE. The CLA is approved. Please go ahead with the code review and discussion.

**Comment by JefWight** [comment]
Reverted all of the token parsing, updated comments.

**Comment by LaylaLiu** [comment]
Merge all changes in this pull request as commit https://github.com/OData/odata.net/commit/a9321f3b41611f5734419f8557bce3e5bbe8e71e.

**Comment by congysu** [comment]
Thanks @JefWight and @LaylaLiu.

**Pull request closed without merging**
