### PR TITLE
Fix compilation on Linux

### LINKED ISSUE #2406: incorrect case for PublicAPI folder
The last three letters of the path odata.net/src/Microsoft.OData.Edm/PublicApi should be upper case so it compiles on Linux without generating a bunch of RS0016 errors

### Assemblies affected

Current version of Microsoft.OData.Edm

### Reproduce steps

Pull source onto a Linux machine and try to compile Microsoft.OData.Edm project

### Expected result

It would compile

### Actual result

It doesn't compile and yields a whole slew of RS0016 errors as it can't find the shipped and unshipped API files

### PR DESCRIPTION
**Pull request by AntiGuideAkquinet**
### Issues

*This pull request fixes #2406.*

### Description

Renaming the PublicApi directory to PublicAPI fixed compilation on Linux devices. This influences CI/CD pipelines and developers on Linux machines in general.

### Checklist (Uncheck if it is not completed)

- [ ] *Test cases added*
- [ ] *Build and test with one-click build and test script passed*

### CODE REVIEW

**Review by xuzhg — APPROVED** [review]

**Comment by habbes** [comment]
The build pipeline fails due to the following:
image

It seems unrelated to the fix. It could be a flaky test. But there seems to be an issue re-running the pipeline. I will try again later.

**Comment by habbes** [comment]
@AntiGuideAkquinet could you try to re-create this PR from a different branch? I've not been able to re-run the build pipeline on this PR.

**Comment by habbes** [comment]
Or make add a new commit and see whether it triggers the pipeline.

**Comment by habbes** [comment]
I have created a new duplicate PR (https://github.com/OData/odata.net/pull/2549) and rebased changes from master and now the pipeline is running. It seems to have triggered the pipeline for this PR as well.

**Review by habbes — APPROVED** [review]

**Comment by habbes** [comment]
I merged the other PR (https://github.com/OData/odata.net/pull/2549). Closing this one.

**Pull request closed without merging**
