### PR TITLE
CustomUriFunction and CustomUriLiteralPrefixes - #720 and #721 Bugs Fix

### LINKED ISSUE #720: Parsing process of a uri which contains additional segments after a custom uri literal fails
### Assemblies affected
 OData .Net Core 6.15 

### Reproduce steps
Register a Custom Uri Literal.
Trying to parse a uri contains that custom uri literal in addition to other sgements after the custom uri literal.
For example:
"?$filter=LionHeartbeat eq myCustomHeartbeatTypePrefixLiteral'55.9Bla' and ID1 eq 3"

### Expected result
Parsing would work just fine.

### Actual result
Exception is thrown.

### Additional details
Only "LionHeartbeat eq myCustomHeartbeatTypePrefixLiteral'55.9Bla'" works, but if "and ID1 eq 3" is added after (or any other segments,) the parisng process fails.

If the segements come before the custom uri literal, the parsing process works well.

### LINKED ISSUE #721: Exceptions are thrown when using Custom Uri Functions in 'Debug' mode.
### Assemblies affected
 OData .Net Core 6.15

### Reproduce steps
Switch to 'Debug' mode.
Register a new custom uri function which uses complex types in it's parameters.
Trying to parse a uri, for example:
"filter=myComplexFunction(LionHeartbeat, 'BlaBla')". LionHeartbeat is a ComplexType.

### Expected result
Everyting to work fine

### Actual result
Debug.Assert throws exceptions in two places in OData.Core assembly.

### Additional details
Happen only in 'Debug' build mode.
In 'Cover' and 'Release' modes everything works fine as expected.

### PR DESCRIPTION
**Pull request by YogiBear52**
### Issues
Bug Fix #721 - Custom Uri Function throws exceptions in 'Debug' mode.  …
Bug Fix #720 - Parse uri which contains additional segments after a custom uri literal fails.

### Description
#720 Fix Details: Expression Toke LiteralEdmType was not cleared after a CustomTypeLiteral TokenKind.

#721 Fix Details: There are two Asset.Debug that throws if the type is non-primtive type. These Assets are not true so I deleted them - the code know how to hadle complex types.

+

Added some tests to CustomUriLiteralParser and CustomUriFunctions.
For some of these tests, a new 'Color' complex type as added to Lion's entity as a 'FavoriteColor' property.

In this pull request some other classes are added. I have no idea why and how it happened( I am not a git pro Oo).

This is the list of the classes that have been renamed in the past and should not be in this commit:
src/Microsoft.OData.Core/UriParser/CustomUriTypePrefixLiterals.cs
src/Microsoft.OData.Core/UriParser/Parsers/TypeParsers/Common/IUriTypeParser.cs
src/Microsoft.OData.Core/UriParser/Parsers/TypeParsers/Common/UriTypeParsingException.cs
src/Microsoft.OData.Core/UriParser/Parsers/TypeParsers/DefaultUriTypeParser.cs
src/Microsoft.OData.Core/UriParser/Parsers/TypeParsers/UriCustomTypeParsers.cs
src/Microsoft.OData.Core/UriParser/Parsers/TypeParsers/UriPrimitiveTypeParser.cs
Microsoft.OData.Core.Tests/UriParser/Parsers/UriCustomTypeParserTests.cs
Microsoft.OData.Core.Tests/UriParser/Parsers/UriCustomTypePrefixLiteralTests.cs

This is the list of changes that I have no Idea what are they and how they got into this pull request:
test/PerformanceTests/ComponentTests/ExecuteTests.ps1
ComponentTests/ODataReader/PayloadTemplate/BasicEntry.json
ComponentTests/ODataReader/PayloadTemplate/EntryExcludeSpatialData.json
ComponentTests/ODataReader/PayloadTemplate/EntryWithExpansionsExcludeSpatial.json

Actually, this is the commit I have wanted to check in(In my repositry):
@https://github.com/OData/odata.net/commit/6689292df976c5fd824b6c21d8629f6cbe8b4efe

Sorry for the mess.

### Checklist (Uncheck if it is not completed)
- [ V ] Test cases added
- [ V ] Build and test with one-click build and test script passed

### Additional work necessary
No additional docs are needed - only bugs fix

### CODE REVIEW

**Comment by mikepizzo** [comment]
We would love to take this PR against the 7.x branch if we can clean it up and target that branch.

**Comment by xuzhg** [comment]
@YogiBear52 Would you please update your PR and rebase/target to the new branch? We'd love to merge your change sets into our repository.

**Comment by YogiBear52** [comment]
@xuzhg Can you please resolve the conflicts between the branches?

**Comment by xuzhg** [comment]
@YogiBear52 We updated the branches. the new "master" branch now targets the "ODataV4-7.x" while "ODataV4-7.x" will be removed later. The new "master" branch is the location in where we'd love to merge your change-set. So, please help rebase your change-set to the new "master" branch.

**Comment by xuzhg** [comment]
@YogiBear52 If it's hard to rebase to the new "master" branch, would you please rebase to "ODataV4-6.x"?Then I can help to port to "master" branch. Thanks a lot.

**Comment by robward-ms** [comment]
@YogiBear52 -Looks like this change still has some conflicts with master. Did you want to rebase on to master?

**Comment by robward-ms** [comment]
@YogiBear52 - You change now has 250+ commits and 3775 changed files after the merge. Have you tried rebasing your change on top of master?

**Comment by manivannanse** [comment]
@YogiBear52  - Did you get a chance to rebase on top of master?

**Comment by xuzhg** [comment]
@YogiBear52 I have to close this PR. If you have any concern, please re-open it with changes or send us a new PR. Thanks your contribution.

**Pull request closed without merging**
