### PR TITLE
json batch response with accept header application/json

### PR DESCRIPTION
**Pull request by biaol-odata**
### Issues
*json batch response -- test passed.*  

### Description
*json batch response with accept header application/json.*

### Checklist (Uncheck if it is not completed)
- [ x ] Test cases added
- [ x ] Build and test with one-click build and test script passed

### Additional work necessary
*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

### CODE REVIEW

**Comment by biaol-odata** [comment]
@mikepizzo is added to the review. #Closed

**Comment by biaol-odata** [comment]
@markdstafford is added to the review. #Closed

**Comment by biaol-odata** [comment]
@robward-ms is added to the review. #Closed

**Comment by biaol-odata** [comment]
@manivannanse is added to the review. #Closed

**Comment by mikepizzo** [comment]
Superseded by PR #779.

**Pull request closed without merging**
