### PR TITLE
O data v4 7.x - Parsing of AnnotationPath and IncludeInServiceDocument attributes

### PR DESCRIPTION
**Pull request by i040628**
### Issues
*This pull request fixes issue #525 and #526*  

### Description
*Added parsing of AnnotationPath attribute as an Expression and parsing of IncludeInServiceDocument attribute for EntitySet in CsdlDocumentParser
Updated classes and interfaces for supporting the new attributes
Added a functional test with a sample metadata document*

### Checklist (Uncheck if it is not completed)
- [ x ] Test cases added
- [ x ] Build and test with one-click build and test script passed

### Additional work necessary
*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

### CODE REVIEW

**Comment by markdstafford** [comment]
Hi @i040628, we'd love to take a look at this PR, but right now it appears to be based on an older version of our code. Could you rebase and update the PR, please? Also, we will need you to electronically sign the CLA if we want to accept the PR.

**Comment by i040628** [comment]
Hi Mark,

my commit to my fork's ODataV4-7.x branch is based on commit "Add test cases for DotNetCore". I fetched the OData repository and the latest commit I see for version 4.7 is the same (made on Nov 15). I don't see the differences between my fork and the OData repository.
Which version do you mean I should rebase on?
I sent now the signed cla via mail.

Thanks and regards,
Peter

**Comment by i040628** [comment]
Hi Mark,

thanks, sounds good.:)
I now created PR 745 (https://github.com/OData/odata.net/pull/745) with my fork for 7.x and looks better I think.
Sorry, I did not have experience with creating PR on github.

Let me know if I have to do some more changes.

Thanks and regards,
Peter

**Comment by markdstafford** [comment]
No problem whatsoever, Peter - we always appreciate contributions, especially from new contributors! I'll go ahead and close this PR and will try to take a look at the other PR later today or early next week.

**Pull request closed without merging**
