### PR TITLE
Continue on [#1298] Support for OData $count operations as per v4.01 spec section 11.2.10  feature

### PR DESCRIPTION
**Pull request by xuzhg**
### Issues

*This pull request continues on PR #1298.*

### Description

* Fully update the PR #1298
* Modify to pass the build

### Checklist (Uncheck if it is not completed)

- [ ] *Test cases added*
- [ ] *Build and test with one-click build and test script passed*

### Additional work necessary

*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

### CODE REVIEW

**Comment by xuzhg** [comment]
@KanishManuja-MS Thanks. This PR is not labeled "Ready for review". Please ignore it now and I will update it later.

**Comment by joshcomley** [comment]
Other than the conflict, what is necessary to get this PR moving?

**Comment by KenitoInc** [comment]
> Other than the conflict, what is necessary to get this PR moving?

Hey @joshcomley 
Thanks for you contributions so far in relation to support for `$count`
Actually I have started looking into this feature. Specifically on these 2 requests:
`$expand=navProp/$count`
`$select=navProp/$count`
We need first to get the design.

ps: OData core is currently supporting
`$filter=navProp/$count gt 10`
`$filter=collectionValuedProp/$count gt 10`

https://github.com/OData/odata.net/blob/8522ce4a452d8c9f95573665cb56534fbfcb886f/test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs#L374

Lets work together to ensure this feature is realised.
Thanks

**Comment by joshcomley** [comment]
Hi @KenitoInc - thanks for getting back so quick!

In case it is of any use, I have just updated my original PR rebasing onto master, merging with this PR's additions:

https://github.com/OData/odata.net/pull/1298

The tests pass except for one which I think is unrelated to this PR (`Microsoft.OData.Tests.ScenarioTests.UriParser.CustomUriFunctionsTests.AddCustomFunction_ShouldAddFunctionWhichAlreadyExistsAsBuiltInWithSameName_AddAsOverload`).

PR `1298` supports `$expand=navProp/$count` but it doesn't support `$select=navProp/$count`.

**Comment by KenitoInc** [comment]
Resolved by PRs #2051 and #2069

**Pull request closed without merging**
