### PR TITLE
Client-side DateTime support

### PR DESCRIPTION
**Pull request by AlanWong-MS**
### Issues
#1151

### Description
Adding client-side DateTime implementation and corresponding test cases.

### Checklist (Uncheck if it is not completed)

- [x] *Test cases added*
- [x] *Build and test with one-click build and test script passed*

### CODE REVIEW

**Comment by xuzhg** [comment]
DateTime was the part of Edm.Primititive. In OData V4, it's removed from the spec to meet the requirement for OASIS standard. I think it's better to sync with @mikepizzo about the supporting for DateTime.

**Comment by AlanWong-MS** [comment]
Got it, thanks for the heads up.

**Comment by seanrodda** [comment]
Is this change included in the recently release version 7.5.0 of the client library? I notice this mentions being merged into master on May 11, however it is still "in progress" with some recent changes 5 days ago. Just wondering what, if anything, was included in 7.5.0. 
Thanks

**Comment by AlanWong-MS** [comment]
@seanrodda, yes it should be included in 7.5.0. Thanks for bringing up the note. You can refer to #1152 to see what changes were included.

**Pull request merged**
