### PR TITLE
Odata v4 7.x - Fix #530 WRONG BRANCH

### LINKED ISSUE #530: LINQ query generation with Date functions produces weird urls
Question: LINQ query  to url generation wrong when using Dates in where clauses? 
Using the OData .NET client with LINQ queries and service implemented with OLingo.
### Assemblies affected

OData .NET client  lib 6.15-beta
### Reproduce steps

Write a linq query with a where clause one a time stamp e.g.
where x.creationTime.hour >=0..
### Expected result

Not sure if this a bug. Maybe another url should be generated or Or our service implementation is wrong.
### Actual result

weird url with path in querystring is generated.
Malformed Url exception is thrown.
### Additional details

The following two tests succeed in producing a wrong url:

```
/// <summary>
/// Using date function in a where clause does not work. The url generated is wrong.
/// </summary>
[Fact]
public void DocumentsDateHourGeZeroLinqDoesNotWork()
{

  var ctx = CreateContext();
  var fakedSessionIds = PostFakeSessions(ctx, 3);

  try
  {
    Action action = () =>  {var fakedDocuments = (from doc in ctx.Documents where doc.CreationDate.Value.Date.Hour >= 0 select doc).ToArray(); };
    Assert.Throws<DataServiceQueryException>(action);

  }
  finally
  {
    DeleteDocuments(ctx, fakedSessionIds);
  }
}

/// <summary>
/// Using date function in a where clause does not work. The url generated is wrong.
/// </summary>
[Fact]
public void DocumentsDateHourGeZeroNoLINQExpressionsDoesNotWork()
{
  var ctx = CreateContext();
  var fakedSessionIds = PostFakeSessions(ctx, 3);

  try
  {
    Action action = () => { var fakedDocuments = ctx.Documents.Where((doc) => doc.CreationDate.Value.Date.Hour >= 0).ToArray(); };

    Assert.Throws<DataServiceQueryException>(action);                 
  }
  finally
  {
    DeleteDocuments(ctx, fakedSessionIds);
  }
}
```

the url generated is:

`https://server.example.com/odata/ODataServlet/Documents?$filter=creationDate/Date/Hour%20ge%200`

The following test produces the right result:

```
    /// <summary>
    /// Using date function in hand crafted url does work
    /// </summary>
    [Fact]
    public void DocumentsDateHourGeZeroNoLINQ()
    {
      var ctx = CreateContext();
      var fakedSessions = PostFakeSessions(ctx, 3);

      try
      {
        const string path = "/odata/ODataServlet/Documents?$filter=hour(creationDate) ge 0";
        var uri = new Uri(Service.Default.host, path);

        var t = ctx.ExecuteAsync<DocumentContent>(uri, "GET");
        t.Wait();

        Assert.Equal(TaskStatus.RanToCompletion, t.Status);
        Assert.NotNull(t.Result);
        var documents = t.Result.ToArray();
        Assert.True(documents.Any());
        Assert.False((from doc in documents where doc.CreationDate.Value.Hour < 0 select doc).Any());

      }
      catch(AggregateException ex)
      {
        throw ex.InnerExceptions.FirstOrDefault();
      }
      finally
      {
        DeleteDocuments(ctx, fakedSessions);
      }
    }
```

The url generated is:
`http://server.example.com/odata/ODataServlet/Documents?$filter=hour(creationDate)%20ge%200`

### PR DESCRIPTION
**Pull request by donchak**
### Issues

*This pull request fixes issue #530.*

### Description

*The DateTimeOffset.Date method was added to the TypeSystem class.*
*Also corresponding methods were added for the DateTime class to make work expressions like this `dateTimeOffsetProperty.Date.Hour`*

### Checklist (Uncheck if it is not completed)

- [x] *Test cases added*
- [x] *Build and test with one-click build and test script passed*

### CODE REVIEW

**Comment by biaol-odata** [comment]
@donchak shouldn't close this one until it is merged.

**Comment by biaol-odata** [comment]
I have just triggered a PR build.

**Comment by biaol-odata** [comment]
hmm, somehow the PR build was not triggered therefore no tests were run with your changes. Some for the PR #1062 on the maintenance-6.x branch. We will need to look into that and ensure PR builds are functioning. Thanks for your patience.

**Comment by biaol-odata** [comment]
@donchak OK, we figured out the possible reason for your PR builds. Can you please target your merge in this PR to the OData:master branch? 
The ODataV4-7.x has become obsoleted, see https://github.com/OData/odata.net/blob/master/README.md. Sorry for the confusion.

**Comment by donchak** [comment]
@biaol-odata Sorry for my misundrestanding. Changing target branch didn't do the trick, so I have created yet another PR for the master branch - https://github.com/OData/odata.net/pull/1068

**Pull request closed without merging**
