### PR TITLE
Add support for further KeyAttributes

### PR DESCRIPTION
**Pull request by boppbo**
### Issues

*This pull request fixes issue #150 .*

### Description

*Some customers don't want to include the odata-dependency on their DTOs to use the key attribute. This PR allows them to use their own key attribute (including the DataAnnotations KeyAttribute) without adding further dependencies.*

### Checklist (Uncheck if it is not completed)

- [  ] Test cases added
    - Elaborate which tests are required, as I can't find any for the current implementation
- [  ] Build and test with one-click build and test script passed
    - Script doesn't work for VS17.3, builds fine using VS
### Additional work necessary

*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

### CODE REVIEW

**Comment by robward-ms** [comment]
@boppbo - Looks like this change is not building completely. Are you using build.cmd?  Here are the build errors:

2017-08-22T16:21:22.4056481Z "C:\BuildAgent\_work\20\s\sln\OData.NetStandard.sln" (default target) (1) ->
2017-08-22T16:21:22.4056481Z "C:\BuildAgent\_work\20\s\sln\..\src\Microsoft.OData.Client\Build.NetStandard\Microsoft.OData.Client.NetStandard.csproj.metaproj" (default target) (6) ->
2017-08-22T16:21:22.4056481Z "C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Build.NetStandard\Microsoft.OData.Client.NetStandard.csproj" (default target) (7) ->
2017-08-22T16:21:22.4056481Z (CoreCompile target) -> 
2017-08-22T16:21:22.4056481Z   C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Metadata\ClientTypeUtil.cs(417,71): error CS1061: 'CustomAttributeData' does not contain a definition for 'Constructor' and no extension method 'Constructor' accepting a first argument of type 'CustomAttributeData' could be found (are you missing a using directive or an assembly reference?) [C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Build.NetStandard\Microsoft.OData.Client.NetStandard.csproj]
2017-08-22T16:21:22.4056481Z   C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Metadata\ClientTypeUtil.cs(417,97): error CS1061: 'CustomAttributeData' does not contain a definition for 'Constructor' and no extension method 'Constructor' accepting a first argument of type 'CustomAttributeData' could be found (are you missing a using directive or an assembly reference?) [C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Build.NetStandard\Microsoft.OData.Client.NetStandard.csproj]
2017-08-22T16:21:22.4056481Z   C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Metadata\ClientTypeUtil.cs(417,137): error CS1061: 'CustomAttributeData' does not contain a definition for 'Constructor' and no extension method 'Constructor' accepting a first argument of type 'CustomAttributeData' could be found (are you missing a using directive or an assembly reference?) [C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Build.NetStandard\Microsoft.OData.Client.NetStandard.csproj]
2017-08-22T16:21:22.4056481Z   C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Metadata\ClientTypeUtil.cs(419,36): error CS1061: 'Type' does not contain a definition for 'GetCustomAttributesData' and no extension method 'GetCustomAttributesData' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?) [C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Build.NetStandard\Microsoft.OData.Client.NetStandard.csproj]
2017-08-22T16:21:22.4056481Z   C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Metadata\ClientTypeUtil.cs(423,51): error CS1061: 'PropertyInfo' does not contain a definition for 'GetCustomAttributesData' and no extension method 'GetCustomAttributesData' accepting a first argument of type 'PropertyInfo' could be found (are you missing a using directive or an assembly reference?) [C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Build.NetStandard\Microsoft.OData.Client.NetStandard.csproj]
2017-08-22T16:21:22.4056481Z   C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Metadata\ClientTypeUtil.cs(429,45): error CS1503: Argument 1: cannot convert from 'TSource[]' to 'string' [C:\BuildAgent\_work\20\s\src\Microsoft.OData.Client\Build.NetStandard\Microsoft.OData.Client.NetStandard.csproj]
2017-08-22T16:21:22.4056481Z

**Comment by robward-ms** [comment]
@boppbo - Have you been able to take a look at the build failure associated with this change?

**Comment by boppbo** [comment]
Hi, sorry for the delay. This code was written long before .net standard was a thing.
I tried to to port it and will report back after having got it tested.

**Comment by robward-ms** [comment]
@boppbo  - Thanks. FYI, we have a neat enhancement you'll notice under "All checks have passed". We automatically kick off a CI build with our change on each PR update. So your push for https://github.com/OData/odata.net/pull/950/commits/bd2b5ec52d719ab4f08cbdfe7c44c19fdf16f067 started a build and it passed all tests.

However, I don't see any tests being added as part of the change. Please add an XUnit test or two to cover the new functionality.

**Comment by xuzhg** [comment]
@boppbo Are you working on the test cases?

**Comment by robward-ms** [comment]
@boppbo Are you working on the test cases?

**Comment by AlanWong-MS** [comment]
@boppbo, thank you for the contribution and work thus far. We strive to provide quick support for PRs, such as yours, and merge them to the source code where appropriate. We noticed that there hasn't been activity on your PR in the last 30 days and because of this, we are considering moving it to a closed state until you are have the opportunity to continue adding to the PR. Doing so allows us to devote the same level of attentiveness to other contributors’ PRs. Within the next two weeks, we'd like to know where you are with the contribution before we decide to park it in "Closed". Thank you for your understanding!

**Comment by AlanWong-MS** [comment]
@boppbo, again, we highly appreciate the time and energy you contributed to the project. It seems that currently may not be the best time to merge the change due to your schedule, so we will park the PR in a "Closed" state. Should you find a good opportunity to move forward with the contribution, please feel free to comment on this PR or open a separate one. Thank you!

**Pull request closed without merging**
