### PR TITLE
Fixed the handling of empty http attributes in Batch Requests 

### PR DESCRIPTION
**Pull request by apiaskowski**
### Issues

[*This pull request fixes Issue-2656*](https://github.com/OData/odata.net/issues/2656)

### Description

OData batching does return an HTTP 500 error, if the request includes a empty `null` value HTTP attributes.
This issue is caused by not proper validation of the JSON property value, when serializing it into a String variable.

### Checklist (Uncheck if it is not completed)

- [x] *Test cases added*
- [x] *Build and test with one-click build and test script passed*

### Additional work necessary

The current implementation does handle empty http attributes, by validating, if the JSON property is empty, i.e. `null`.
But as discussed in previous [PR-2669](https://github.com/OData/odata.net/pull/2669), these should not be handled in this way and instead throw an `ODataException`.
If so, the odata specification need to be adjusted and highlight, that empty http attributes / JSON properties are not allowed.

### CODE REVIEW

**Comment by apiaskowski** [comment]
@gathogojr would it be possible to review this follow-up task of [PR-2669](https://github.com/OData/odata.net/pull/2669)?

**Comment by gathogojr** [comment]
Hi @apiaskowski We do squash the commits when merging but a reviewer who's not familiar with the background might wonder and indeed ask why there are so many commits. If it's not too much of a hassle, consider squashing them.

**Review by gathogojr — APPROVED** [review]
:shipit:

**Review by KenitoInc — APPROVED** [review]

**Comment by apiaskowski** [comment]
> Hi @apiaskowski We do squash the commits when merging but a reviewer who's not familiar with the background might wonder and indeed ask why there are so many commits. If it's not too much of a hassle, consider squashing them.

Sure, I'll do. Typically I'd "squash & merge", but since I am not able to do so here, I'd have to do it here manually by git rebase?

**Comment by gathogojr** [comment]
> > Hi @apiaskowski We do squash the commits when merging but a reviewer who's not familiar with the background might wonder and indeed ask why there are so many commits. If it's not too much of a hassle, consider squashing them.
> 
> Sure, I'll do. Typically I'd "squash & merge", but since I am not able to do so here, I'd have to do it here manually by git rebase?

Yeah. Basically `git rebase i HEAD~N` where N is the number of commits you want squash and merge. If it becomes a challenge/too much work, just leave it be. I can just squash and merge from here...

**Pull request merged**
