### PR TITLE
Support for vocabulary annotations on Enum members

### PR DESCRIPTION
**Pull request by mijin2185**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mijin2185__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by MrTomWhite** [comment]
Could we add some unit tests to this PR? In particular, we want to be sure that we can get annotations on enum members deserialized...

Quoting from #71 which tracks this issue, 
>Additionally, if an Edm Enum member has annotations, Microsoft.OData.Core.ODataMessageReader fails when parsing the metadata document with an unexpected annotation exception.

`Core.Description` would be a decent annotation to use for a test case, but if you have a more specific use case that'd be fine too. 

This also looks relevant to @Laylaliu 's interests, since they're assigned on this issue. 

Also, like the PR bot said, don't forget to fill out a CLA and send it back promptly @mijin2185

**Comment by mijin2185** [comment]
Where should the unit tests be added?  How exactly do you want to test deserialization of annotations of enum members?  Are there any existing tests that I can use as a starting point?

**Comment by karataliu** [comment]
Hi, @mijin2185 
For CsdlDocumentParser change, you can refer to VocabularyParsingTests class.
You can add one case similar to ParsingValueAnnotationWithTrueBooleanValue, write a CSDL with annotation under EnumMember element, parse it and validate the value.

For EdmEnumMember change, you refer to ConstructibleVocabularyAnnotationsTests class.
You may modify one case by adding the an EdmEnumMember instance with annotation and do validation.

**Comment by LaylaLiu** [comment]
Have squashed this commit into the "Support annotations on enum member #96“ pull request

**Comment by congysu** [comment]
Thanks @MrTomWhite for your help, and also @mijin2185 for submitting a pull request.  Looking forward to more contributions from both of you.  Set the label as cla-not-required, since @mijin2185 is an MS employee.

**Pull request closed without merging**
