### PR TITLE
Allow for intented printing to include newline character seperators

### PR DESCRIPTION
**Pull request by peternied**
Looks like even though there is a line intender that will do a good job lining up subsequent lines, there is a missing write line where the member objects will not be on a fresh line.  This should enhance the unaided readability quite a bit.

### CODE REVIEW

**Comment by peternied** [comment]
Ping!

**Comment by bixu-ms** [comment]
Hi @peternied, if you want the pretty print, you can set the ODataMessageWriterSettings.Indent to true, then the json output would contains indention and newline.
It is turned off by default to save the space.

**Comment by peternied** [comment]
Yes that is true, and also this pull request is done to make that code usable.  This is a fix to make sure that the indented code is readable as right now you can generate code like so:

"stuff":{
   "foo":"bar", "wishy":"washy", "belly":"button", "innerStuff":
   {
   }
}

With the fix it will look like so:

"stuff":{
   "foo":"bar",
   "wishy":"washy",
   "belly":"button"
   "innerStuff":
   {
   }
}

This is very evident with long names or names that contain namespaces.

**Comment by peternied** [comment]
Thanks for the review and suggestions!

**Comment by bixu-ms** [comment]
@peternied Sorry for the the late response, we just had our new year vacation. The code now looks fine. However, before we merge the code, can you also help to take a look at the test cases impacted by this fix?

**Comment by peternied** [comment]
Is there a guide on how to run them, I don't see them contained within the solution.

**Comment by peternied** [comment]
I see that you've been hard at work and have completely reconstructed this project, I found the multitudes of test cases, and I'm unable to see them all passing.  I take it this is due to some missing pre-reqs like a SQL instance.  The idea of troubleshooting your newly complex solution these 3 lines does not seem worthwhile, so I'm abandoning this change.

**Pull request closed without merging**
