### PR TITLE
Added basic support for aggregations spec

### PR DESCRIPTION
**Pull request by kosinsky**
Support for ApplyClause (with groupby, aggregate and filter transformations)

### CODE REVIEW

**Comment by ronnyek** [comment]
@kosinsky any chance this is something you can sign cla for? I'm excited to check this functionality out

**Comment by kosinsky** [comment]
@ronnyek I'm working on it.

**Comment by congysu** [comment]
Thanks @ronnyek.  @kosinsky is an MS employee.  I've updated the cla status.

**Comment by VikingsFan** [comment]
Merged with 9bece447c80bd7352010383cfa8dd75b6d72bccf & 3b73363e088ad9e6909c7e0f9cb73b134c38a9c7 , Changes:Remove dynamic entity type, use open property feature, $apply=..& $filter=OpenProperty eq 1 won't work, but $apply=../filter(OpenProperty eq 1) is working. 

Thanks Fan

**Pull request closed without merging**
