### PR TITLE
Odata v4 6.x - Fix #530 LINQ query generation with Date functions produces weird urls

### LINKED ISSUE #530: LINQ query generation with Date functions produces weird urls
Question: LINQ query  to url generation wrong when using Dates in where clauses? 
Using the OData .NET client with LINQ queries and service implemented with OLingo.
### Assemblies affected

OData .NET client  lib 6.15-beta
### Reproduce steps

Write a linq query with a where clause one a time stamp e.g.
where x.creationTime.hour >=0..
### Expected result

Not sure if this a bug. Maybe another url should be generated or Or our service implementation is wrong.
### Actual result

weird url with path in querystring is generated.
Malformed Url exception is thrown.
### Additional details

The following two tests succeed in producing a wrong url:

```
/// <summary>
/// Using date function in a where clause does not work. The url generated is wrong.
/// </summary>
[Fact]
public void DocumentsDateHourGeZeroLinqDoesNotWork()
{

  var ctx = CreateContext();
  var fakedSessionIds = PostFakeSessions(ctx, 3);

  try
  {
    Action action = () =>  {var fakedDocuments = (from doc in ctx.Documents where doc.CreationDate.Value.Date.Hour >= 0 select doc).ToArray(); };
    Assert.Throws<DataServiceQueryException>(action);

  }
  finally
  {
    DeleteDocuments(ctx, fakedSessionIds);
  }
}

/// <summary>
/// Using date function in a where clause does not work. The url generated is wrong.
/// </summary>
[Fact]
public void DocumentsDateHourGeZeroNoLINQExpressionsDoesNotWork()
{
  var ctx = CreateContext();
  var fakedSessionIds = PostFakeSessions(ctx, 3);

  try
  {
    Action action = () => { var fakedDocuments = ctx.Documents.Where((doc) => doc.CreationDate.Value.Date.Hour >= 0).ToArray(); };

    Assert.Throws<DataServiceQueryException>(action);                 
  }
  finally
  {
    DeleteDocuments(ctx, fakedSessionIds);
  }
}
```

the url generated is:

`https://server.example.com/odata/ODataServlet/Documents?$filter=creationDate/Date/Hour%20ge%200`

The following test produces the right result:

```
    /// <summary>
    /// Using date function in hand crafted url does work
    /// </summary>
    [Fact]
    public void DocumentsDateHourGeZeroNoLINQ()
    {
      var ctx = CreateContext();
      var fakedSessions = PostFakeSessions(ctx, 3);

      try
      {
        const string path = "/odata/ODataServlet/Documents?$filter=hour(creationDate) ge 0";
        var uri = new Uri(Service.Default.host, path);

        var t = ctx.ExecuteAsync<DocumentContent>(uri, "GET");
        t.Wait();

        Assert.Equal(TaskStatus.RanToCompletion, t.Status);
        Assert.NotNull(t.Result);
        var documents = t.Result.ToArray();
        Assert.True(documents.Any());
        Assert.False((from doc in documents where doc.CreationDate.Value.Hour < 0 select doc).Any());

      }
      catch(AggregateException ex)
      {
        throw ex.InnerExceptions.FirstOrDefault();
      }
      finally
      {
        DeleteDocuments(ctx, fakedSessions);
      }
    }
```

The url generated is:
`http://server.example.com/odata/ODataServlet/Documents?$filter=hour(creationDate)%20ge%200`

### PR DESCRIPTION
**Pull request by donchak**
### Issues

*This pull request fixes issue #530.*

### Description

*The DateTimeOffset.Date method was added to the TypeSystem class.*
*Also corresponding methods were added for the DateTime class to make work expressions like this `dateTimeOffsetProperty.Date.Hour`*

### Checklist (Uncheck if it is not completed)

- [x] *Test cases added*
- [x] *Build and test with one-click build and test script passed*

### CODE REVIEW

**Comment by biaol-odata** [comment]
@donchak Thanks for your contribution. The fix looks good. However, ODataV4-6.x is a maintenance branch that we don't have concrete date on next release, and our active dev branch is the master branch (for ODL 7.x). Therefore, can you also port the changes here to the master branch? I believe there should be no conflicts therefore should be a straight merge.

**Comment by biaol-odata** [comment]
@mikepizzo FYI, add comments as needed.

**Comment by donchak** [comment]
@biaol-odata Thanks! Sure, I'll prepare a pull request for ODL 7.x.

**Comment by donchak** [comment]
@biaol-odata I have added the pull request: https://github.com/OData/odata.net/pull/1066

**Comment by biaol-odata** [comment]
@donchak Actually you should leave the PR #1066 opened and get it merged into ODL master first. Looks like you need to sign the CLA so that the PR build can proceed. Can you please do that? Thanks.

**Comment by biaol-odata** [comment]
@donchak similar to the PR build issue on the other PR #1066, Can you please target your change in this PR to OData:maintenance-V4, which is the valid branch for ODLV4-6.x? You might need to create a new PR and close this one first. Thanks.

**Comment by donchak** [comment]
@biaol-odata It seems to be fine now.

**Comment by donchak** [comment]
@biaol-odata Sorry, but I can't find the maintenance-V4 branch. Do you mean maintenance-wcf-dataservice-V4 ?

**Comment by biaol-odata** [comment]
@donchak sorry, should be the maintenance-6.x branch.

**Comment by donchak** [comment]
@biaol-odata The branch to merge in this PR is maintenance-6.x now.

**Comment by biaol-odata** [comment]
@donchak Looks like your PR is not rebased correctly to the maintenance-6.x, which has a tip of ab32e8ad.
Your commit d7104ede in this PR is based on a old commit c4882297(from obsoleted branch ODataV4-6.x).
Can you please rebase? Thanks.

**Comment by biaol-odata** [comment]
@donchak Are you still working on this? Can you please rebase as mentioned above? Thanks.

**Comment by donchak** [comment]
@biaol-odata Sorry for the long delay. I didn't find the way to rebase existing PR, so I've created a new one - https://github.com/OData/odata.net/pull/1076.

**Comment by biaol-odata** [comment]
That works. Thanks!

**Pull request closed without merging**
