### PR TITLE
Remove references to ORCAS

### PR DESCRIPTION
**Pull request by ificator**
### Issues

Code still has references to ORCAS

### Description

ORCAS hasn't been in the picture for MANY years so we can safely remove it

### Checklist (Uncheck if it is not completed)

- [x] *Test cases added*
- [x] *Build and test with one-click build and test script passed*

### CODE REVIEW

**Comment by xuzhg** [comment]
@ificator It looks good to me. :shipit:

**Review by gathogojr — APPROVED** [review]
:shipit:

**Comment by habbes** [comment]
Looks good to me.

Any documentation on ORCAS. Curious to know what it was.

**Review by habbes — APPROVED** [review]

**Comment by ificator** [comment]
> Looks good to me.
> 
> Any documentation on ORCAS. Curious to know what it was.

If memory serves it was the codename for VS2005/.NET 2. Back when they were given names of islands around WA state.

**Pull request merged**
