### PR TITLE
Add the missing methods and enums

### PR DESCRIPTION
**Pull request by kbarkhausen**
### Issues

*This pull request fixes issue #1417.*

### Description

Adds the missing methods and related types.

### Checklist (Uncheck if it is not completed)

- [X] Same code that existing in 6.15

### CODE REVIEW

**Comment by kbarkhausen** [comment]
I signed the CLA

**Comment by kbarkhausen** [comment]
> [CLA assistant check](https://cla.opensource.microsoft.com/OData/odata.net?pullRequest=1419) 
> All CLA requirements met.

All checks were not successful before (it was missing my CLA signature) but it should work now. Can you try a new build?

**Comment by xuzhg** [comment]
@kbarkhausen It maybe the publicapitest failed because you add the public api. You should change it.

Besides, It seams customer can create the similar functionality at their side. I mean it's un-necessary to add similiar at ODL core.

**Comment by kbarkhausen** [comment]
I was able to add this missing functionality within my own code so it does seem unnecessary to add to the ODL core.

**Comment by kbarkhausen** [comment]
Closing the fork

**Pull request closed without merging**
