### PR TITLE
Fix argument null exception during projection

### LINKED ISSUE #3037: Client 8.0.0 - Projection fails for navigation property being null
Projection with a navigation property being null throws `System.ArgumentNullException: Value cannot be null. (Parameter 'source')`

### Assemblies affected

This bug were introduced in ODL Client 8.0.0.rc.1 and is still present in ODL 8.0.0. ODL Client 8.0.0.preview.3 and earlier does not have this issue.

### Reproduce steps

Imagine a model with a Person having a navigation property Spouse of type Person that can be null. Then the error can be reproduced with this code (provided that you have people without spouses in your store)...

```
            var q = from p in ctx.People
                    where p.Spouse == null
                    select new Person
                    {
                        ID = p.ID,
                        Spouse = p.Spouse
                    };

            var results = q.ToList();

```

### Expected result

Results are materialized correctly having null as navigation property value.

### Actual result

An exception is thrown when the response is materialized...

    System.ArgumentNullException: Value cannot be null. (Parameter 'source')

    ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
ODataEntityMaterializer.ProjectionValueForPath(MaterializerEntry entry, Type expectedType, ProjectionPath path)
ODataEntityMaterializerInvoker.ProjectionValueForPath(Object materializer, Object entry, Type expectedType, Object path)
lambda_method3885(Closure, Object, Object, Type)
ODataEntityMaterializer.ProjectionInitializeEntity(ODataEntityMaterializer materializer, MaterializerEntry entry, Type expectedType, Type resultType, String[] properties, Func`4[] propertyValues)
lambda_method3886(Closure, Object, Object, Type)
ProjectionPlan.Run(ODataEntityMaterializer materializer, ODataResource entry, Type expectedType)
ODataEntityMaterializer.ReadImplementation()
ObjectMaterializer.MoveNextInternal()
ObjectMaterializer.MoveNext()
Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
List`1.ctor(IEnumerable`1 collection)
Enumerable.ToList[TSource](IEnumerable`1 source)

### PR DESCRIPTION
**Pull request by uffelauesen**
### Issues

*This pull request fixes #3037.*

### Description

Fixes issue in ProjectionValueForPath() when linkEntry.Properties is null bypassing call to OfType<ODataProperty>().

### Checklist (Uncheck if it is not completed)

- [ ] *Test cases added*
- [ ] *Build and test with one-click build and test script passed*

### Additional work necessary

Regression introduced in ODL Client 8.0.0-rc.1

### CODE REVIEW

**Comment by habbes** [comment]
This must be due to change from `ODataProperty` to `ODataPropertyInfo`.

**Comment by habbes** [comment]
The issue was introduced by this PR: https://github.com/OData/odata.net/pull/2916

The root issue is that `ODataResource.Properties` and `MaterializerEntry.Properties` could be null. So may have other places that could break. We should consider adding the null check here as well: https://github.com/OData/odata.net/pull/2916/files#diff-a39b2ec2693141c7a1e515c2b9ca95fb0fd0b3eacc903b92e61a048d07738fe0R253

**Review by gathogojr — DISMISSED** [review]

**Review by gathogojr — APPROVED** [review]

**Comment by habbes** [comment]
Thanks @gathogojr  for adding the tests

**Review by habbes — APPROVED** [review]

**Comment by gathogojr** [comment]
More details from the investigation:

```csharp
var serviceRoot = new Uri("http://localhost:5205");
var ctx = new Container(serviceRoot);

var query1 = from people in ctx.People
            where people.Spouse == null
            select new Person
            {
                Id = people.Id,
                Spouse = people.Spouse
            };
// OData URL: http://localhost:5205/People?$filter=Spouse eq null&$expand=Spouse&$select=Id
var results1 = query1.ToList(); // Throws exception

var query2 = ctx.CreateQuery<Person>("People").Where(p1 => p1.Spouse == null).Select(p2 => new { p2.Id, p2.Spouse });
// OData URL: http://localhost:5205/People?$filter=Spouse eq null&$expand=Spouse&$select=Id
var results2 = query2.ToList(); // Throws exception

var query3 = ctx.People.AddQueryOption("$filter", "Spouse eq null").AddQueryOption("$expand", "Spouse").AddQueryOption("$select", "Id");
// OData URL: http://localhost:5205/People?$expand=Spouse&$filter=Spouse eq null&$select=Id
var results3 = query3.ToList(); // No exception thrown

var query4 = ctx.Execute<Person>(new Uri("http://localhost:5205/People?$expand=Spouse&$filter=Spouse eq null&$select=Id"));
// OData URL: http://localhost:5205/People?$expand=Spouse&$filter=Spouse eq null&$select=Id
var results4 = query4.ToList(); // No exception thrown

var query5 = ctx.Execute<Person>(new Uri("http://localhost:5205/People?$filter=Spouse eq null&$expand=Spouse&$select=Id"));
// OData URL: http://localhost:5205/People?$filter=Spouse eq null&$expand=Spouse&$select=Id
var results5 = query5.ToList(); // No exception thrown! Yet the OData URL mirrors that of the first two query expressions. Projection seems to be where the issue is
```

**Pull request merged**
