### PR TITLE
Added IgnoreClientProperty attribute

### PR DESCRIPTION
**Pull request by riccardozucchetto**
**ISSUES**

This pull fixes issues #103 and https://github.com/OData/RESTier/issues/172 .

**DESCRIPTION**

Added IgnoreClientProperty attribute in order to ignore client-side entity properties added in partial classes. In this way one can extend server-side entity classes with custom properties, being ignored while sending insert or update JSON.

### CODE REVIEW

**Comment by robward-ms** [comment]
I don't see any tests being included in this PR, can you verify the new functionality using our XUnit test projects? You can find some guidance here: https://github.com/OData/odata.net/blob/master/.github/CONTRIBUTING.md

**Comment by robward-ms** [comment]
@riccardozucchetto - I don't see any tests being included in this PR, can you verify the new functionality using our XUnit test projects?

**Comment by riccardozucchetto** [comment]
Hi Rob,
Sorry for the delay, I was on holiday and then I forgot to reply.
I have some problems with the XUnit test projects: I have never used them before, so I do not know really which project to use (I have cloned the whole branch, so I have a bunch of projects) and, moreover, I do not know how to edit them: I mean, to test this attribute I need to have a server-side defined class which is then generated client-side, and then I need to extend it with a property only on the client, decorated with the new attribute. But in the projects I have seen there is only the xml definition of the classes and I do not know how to extend it with a custom client-side property. I have read the Contributing.md file, but it didn't help me very much.
Can I, for instance, create a sample project and attach it? Or can I have some tips on how can I edit the unit tests?

Thank you,
Riccardo

**Comment by robward-ms** [comment]
@riccardozucchetto - You make a very good point. Our client tests are still in legacy test projects, which we don't expect (or want) contributors to update and the current XUnit tests won't easily let you test your new functionality. Because of this, I'll drop the new test requirement for this change.

The automated build is failing, it looks like you need to rebase your change on the latest version of master. Specifically, it does not look like your code contains the recent solution/project refactoring change. This is causing the "All checks have failed".

Can you rebase your change and submit an update? Once it starts passing the build, I'll merge it.

**Comment by riccardozucchetto** [comment]
Hi Rob,
In the next days I'll try to rebase my fork to the latest version of the master branch. Once I have rebased it is there a way to integrate that changes in this pull request? Or should I create a new one?
Thank you for your help, it's the first time I use GitHub to contribute to some projects.

Best regards,
Riccardo

**Comment by robward-ms** [comment]
@riccardozucchetto - Looks like you made this change in your copy of master, which will generally cause you headaches. Using a new branch is usually best. At this point, you should pull from OData's master branch (usually git pull OData master) and which point you may be forced to merge with your change. Go ahead and do that, and once you get that committed, do a git push and it will automatically update the PR. This will result in less-than-desired history in your branch which we'll fix by doing a squash merge.

**Comment by riccardozucchetto** [comment]
Hi Rob,
I have updated my forked branch and it has no conflicts with the base branch. However, as you can see, the buil is still failing.
What should I do?

Thank you,
Riccardo

**Comment by robward-ms** [comment]
@riccardozucchetto ,

This is the build failure:
2017-09-11T13:13:11.4891445Z   C:\BuildAgent\_work\25\s\src\Microsoft.OData.Client\Metadata\ClientTypeAnnotation.cs(217,69): error CS0246: The type or namespace name 'IgnoreClientPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\BuildAgent\_work\25\s\src\Microsoft.OData.Client\Build.NetStandard\Microsoft.OData.Client.NetStandard.csproj]

You have only updated src/Microsoft.OData.Client/Microsoft.OData.Client.csproj , you also need to update src/Microsoft.OData.Client/Build.NetStandard/Microsoft.OData.Client.NetStandard.csproj, src/Microsoft.OData.Client/Microsoft.OData.Client.NetStandard.VS2017.csproj, and src/Microsoft.OData.Client/Build.Portable/Microsoft.OData.Client.Portable.csproj.

If you are using the build.cmd for building and testing, you should see these errors locally. For info on build.cmd, see the readme in this repo.

**Comment by riccardozucchetto** [comment]
Hi Rob,
I have discovered that, with the new version, my code isn't working. I'm using the GetCustomAttributes method, which is not supported in the portable version.
It seems that adding a "using System.Reflection" directive solves the problem (it contains a similar extension method and the msbuild.log file reports a compilation completed result), but I need to test it in our application in order to be sure it works. I think I will be able to test it next week, so as soon as I know if it's working I'll come back to you.
Meanwhile, I have one more question: I am using VS 2015 and our application uses WPF, ASP.NET and Xamarin. We cannot install VS 2017, so how can I be sure that the compilation of the VS 2017 project completes fine? Just by doing a commit and see if it builds right?

Thank you,
Riccardo

**Comment by robward-ms** [comment]
@riccardozucchetto - If you can't install VS2017, a commit and test build is the best way to validate.

**Comment by xuzhg** [comment]
@riccardozucchetto any update so far?

**Comment by riccardozucchetto** [comment]
Hi Sam,
I have updated my fork with the last changes. I launched the build command locally, which completed successfully. I see that there are some problems in the tests, but they don't seem to be related to my changes. However, I see that the build trigger failed. Is there any way I can understand what's wrong and if it depends on my changes? Clicking on "details" leads me to an unauthorized page. I can't test the building for VS 2017, so if that's the problem I won't be able to see it.

Thank you for your help,
Riccardo

**Comment by robward-ms** [comment]
Here is the error, it is in the Microsoft.OData.Client.NetStandard.VS2017 project. Basically, you don't need to change that file:

2017-10-20T07:17:13.2419639Z (CheckForDuplicateItems target) -> 
2017-10-20T07:17:13.2419639Z   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.DefaultItems.targets(165,5): error : Duplicate 'Compile' items were included. The .NET SDK includes 'Compile' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultCompileItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'Attribute\IgnoreClientPropertyAttribute.cs' [C:\BuildAgent\_work\25\s\src\Microsoft.OData.Client\Microsoft.OData.Client.NetStandard.VS2017.csproj]

**Comment by riccardozucchetto** [comment]
Hi Rob,
So, if I'm right and you agree, tomorrow morning I will remove the duplicated line from the project you indicated (I added that line in a previous commit) and (hopefully) everything should work correctly. I will do it and push the commit to see the results, because I'm not able to test it locally as you know.

Thank you,
Riccardo

**Comment by robward-ms** [comment]
I verified that change will fix the build problems but it will fail the public API unit test since you added a new public attribute and did not update the public api baseline in your change. If you run PublicApiTest, it will provide a cmd line to update the baseline. Do that and include it with your change to the *.2017.csproj.

**Comment by AlanWong-MS** [comment]
@riccardozucchetto, heads up: we recently committed some changes to the master branch that you'll have to pull. The build check will fail without the new changes.

**Comment by robward-ms** [comment]
@riccardozucchetto - We had a change merge to master last night that would require you to merge your change with it to pass the build. However, you've been through a lot with this change so I'm rebasing it on top of the latest master will verify and check it in directly. Let me know if you don't want that to happen.

**Comment by riccardozucchetto** [comment]
Hi Rob,
I totally agree with you, so please rebase it; I will check for any problem after the rebase and check in.

Thank you very much!
Riccardo

**Comment by robward-ms** [comment]
rebased and merged manually: https://github.com/OData/odata.net/commit/70b310a4765cd3e1685db06470204ea38b03def9

Build has passed compilation and all tests, look good. Change will be available in the nightly build dates  2017/10/27.

**Comment by riccardozucchetto** [comment]
Hi Rob,
Thank you very much for your patience and for your help!

Riccardo

**Comment by robward-ms** [comment]
@riccardozucchetto  - Thanks for YOUR patience.

**Pull request closed without merging**
