### PR TITLE
Ignore Null Values in output

### PR DESCRIPTION
**Pull request by kosinsky**
Ignoring null values during serialization to improve performance and decrease output size in case of sparse entities.

Behavior controlled by ODataWriterSettings and disabled by default

### CODE REVIEW

**Comment by mikepizzo** [comment]
Support for requesting and receiving an output that omits null values was added to the OASIS OData specification as an "omit-values" preference.  See http://docs.oasis-open.org/odata/odata/v4.01/csprd01/part1-protocol/odata-v4.01-csprd01-part1-protocol.html#_Toc470092999. Omitting null values only when requested by the client, and making sure the response has omit-values in the preference applied header to say that nulls were omitted is important for interoperability.

If this PR can be updated to use the omit-values=null preference I would love to take it.

**Comment by kosinsky** [comment]
Great, I'll work on updating that PR to follow 4.0.1

**Comment by xuzhg** [comment]
@kosinsky Please rebase the commit and target to the new branch. Thanks

**Comment by biaol-odata** [comment]
@kosinsky: Hi Konstantin, have you completed the rebase the change to the master branch? We are considering cleaning up the old branches, so please write back if your changes are not completely moved yet. Thanks!

**Comment by kosinsky** [comment]
@biaol-odata Done. Had to close that PR and start from scratch to be able to use new source branch on my side

**Comment by biaol-odata** [comment]
Thanks Konstantin.

**Pull request closed without merging**
